[package]
name = "zane"
version = "0.1.0"
edition = "2024"

[dependencies]
gi-ui-app = { git = "https://github.com/NDRAEY/gi-ui-app", version = "0.1.0" }
gi-ui = { git = "https://github.com/NDRAEY/gi-ui", version = "0.1.0", default-features = false, features = ["text8x8"] }
nimage = "0.1.4"
